[package]
name = "rocket_codegen"
version = "0.4.0-rc.1"
authors = ["Sergio Benitez <sb@sergio.bz>"]
description = "Procedural macros for the Rocket web framework."
documentation = "https://api.rocket.rs/v0.4/rocket_codegen/"
homepage = "https://rocket.rs"
repository = "https://github.com/SergioBenitez/Rocket"
readme = "../../README.md"
keywords = ["rocket", "web", "framework", "code", "generation"]
license = "MIT/Apache-2.0"
build = "build.rs"

[lib]
proc-macro = true

[dependencies]
indexmap = "1.0"
quote = "0.6.1"
rocket_http = { version = "0.4.0-rc.1", path = "../http/" }
devise = "0.1"

[build-dependencies]
yansi = { git = "https://github.com/SergioBenitez/yansi", rev = "59c3a91" }
version_check = "0.1.3"

[dev-dependencies]
rocket = { version = "0.4.0-rc.1", path = "../lib" }
compiletest_rs = { git = "https://github.com/laumann/compiletest-rs" }
